web_service_init:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: uddi }

web_service:
    resource: "@WebServiceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/service
    requirements:
        _locale: en|es

web_service_uddi:
    resource: "@WebServiceBundle/Resources/config/routing/uddi.yml"
    prefix: /{_locale}/uddi
    requirements:
        _locale: en|es

web_service_server:
    resource: "@WebServiceBundle/Resources/config/routing/server.yml"
    prefix: /

xalix_ws:
    type: rest
    prefix: /
    resource: "@WebServiceBundle/Resources/config/routes.yml"