protocol:
    pattern:  /
    defaults: { _controller: "WebServiceBundle:Protocol:index" }

protocol_configure:
    pattern:  /{id}/{action}
    defaults: { _controller: "WebServiceBundle:Protocol:configure" }
